### ISSUE TITLE
how to apply the textures and armature?

### ISSUE THREAD

**Issue by NoName43369** [soevielofficial/wuwa-assets#3]
I'm new to using 3d modeling softwares. I want to know how can I apply the textures using the json files and which software should I use in order not to encounter bugs.

**Comment by soevielofficial** [comment]
you can import psk mesh using [this](https://github.com/matyalatte/blender3d_import_psk_psa) blender plugin. after that you can apply texture to the psk mesh

**Comment by NoName43369** [comment]
thanks, it helped a lot

**Comment by soevielofficial** [comment]
no problem
